### ISSUE TITLE
Align on deadline for items to be in put in correct status

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2023ss01-apache-pulsar-ui#58]
**Description:**
Align as a group on a deadline until which all finished items should be put in status Awaiting review

**Risks if not done:**

- Not finishing all of the planned tasks. 
- Not using free developer capacity to support team mates

**Comment by ahaverkamp** [comment]
We decided on the following: 

By 6pm Tuesday, all developers need to drag their features to the correct column in the feature board so that the POs can put the appropriate screenshots of the docs in the deliverables folder Tuesday evening/night.
Then the release manager can create the release candidate hopefully without problems or anything missing on Wednesday morning. 

Also, by Tuesday night, all features must be merged into the master, provided they work and the tests are green. Again, so that the release manager doesn't have any problems on Wednesday.

**Comment by emiliakaf** [comment]
everyone commited to the deadline

**Comment by emiliakaf** [comment]
closing , as it is adopted as a practice
